name: make-lint
on: 
  - push
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: my-step
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: true
      - run: make install
      - run: make lint
